pypa/build

- .github/workflows/build.yml
- pyproject.toml
Flit doesn't allow us to specify the packages/modules to install.
> pyproject: move to poetry

- build/__init__.py
- tests/test_projectbuilder.py
The toml backtrace is still available for API consumers if they want it.
> build: raise BuildException when fail to parse pyproject.toml

- README.md
> readme: add PyPA CoC

- build/__init__.py
- build/__main__.py
- tests/test_main.py
- tests/test_projectbuilder.py
> build: fix typo in ProjectBuilder.get_dependencies()

- noxfile.py
Without this, `nox` fails.
If we're going to have a `noxfile.py`, I think it should be used in the CI as well, so that we can expect contributors to be able to just run `nox` or `nox -s test-3.8` or whatever and it should always work.
Here's how I typically do it when I use `tox` in my projects: https://github.com/pganssle/zoneinfo/blob/4299bfd7623934acc6f27b32744b02a147912120/.github/workflows/python-tests.yml#L5-L32
I think that you'd do something similar by parameterizing over `NOXSESSION`.
> nox: add pytest-mock dependency

- .github/workflows/build.yml
- build/__init__.py
- build/__main__.py
- build/env.py
- docs/source/index.rst
- tests/conftest.py
- tests/test_env.py
- tests/test_main.py
- tests/test_projectbuilder.py
As discussed in [1] python-build should now build inside a virtual
environment, as recommended in PEP517. This patch implements that
functionality and sets it as the default behavior. It also introduces a
--no-isolation flag to disable this.
[1] https://discuss.python.org/t/moving-python-build-to-pypa/4390
> main: build in a virtual env by default

- src/build/env.py
- tests/test_env.py
This is required so that we can find programs such as GCC.
> env: keep original PATH

- .github/workflows/checks.yml
- .github/workflows/tests.yml
This makes the CI run all jobs even if one failed. This way we can see
exactly all of the breakage.
> ci: disable fail-fast

- src/build/__init__.py
- tests/test_projectbuilder.py
> build: include build system dependencies in check_dependencies

- src/build/__main__.py
- src/build/env.py
- tests/test_env.py
This makes it easier to reuse IsolatedEnvironment on environments other than the current intrepreter, and likely also would make it easier to test since the introspection rules can not be more easily mocked.
> Detach interpreter introspection from other logic

- .github/workflows/tests.yml
> ci: always upload coverage reports

- setup.cfg
> setup.cfg: add trove classifieres for CPython and PyPy

- src/build/__init__.py
- tests/test_projectbuilder.py
> build: create output directory if missing

- src/build/__init__.py
- tests/test_projectbuilder.py
Right now we are trying to check for in-tree backends, which obviously
won't work.
We only have this check to provide nicer error messages to users, I
don't see the need to provide the same "nicer" error messages when using
in-tree backends as it is quite niche.
In these cases, pep517 will raise an error and we will print it.
> build: do not check for the backend in when using in-tree backends

- tests/conftest.py
- tests/test_integration.py
flit_core uses an in-tree backend
> tests: integration: test building flit_core 

- README.md
For details, see:
* https://discuss.python.org/t/implementing-pep-609-pypa-governance/4745
> The PyPA has adopted the PSF code of conduct

- README.md
Hi! (Congrats on the release).
Perhaps it's useful to add an installation command to the README, mostly considering that `python-build` on PyPI is an [unrelated thing](https://pypi.org/project/python-build/) so folks need to know this has a distribution name of just `build`.
> readme: add an install command

- .github/workflows/checks.yml
- .github/workflows/docs.yml
- .github/workflows/tests.yml
- .pre-commit-config.yaml
- docs/source/build.rst
- docs/source/conf.py
- docs/source/index.rst
- noxfile.py
- src/build/__main__.py
- src/build/env.py
- Adds the install command from #94 to the Sphinx docs
- Fixes the warnings from building the docs, including populating the missing API documentation
- Builds docs in CI more strictly than RTD to catch bugs such as the above
- Tidies up the intro slightly
- Mentions PyPy in the supported versions
- Links to options when mentioned
- Sets `default_role` so future documentation doesn't have to be as verbose
- Updates the language around comparing to `pep517-build` to mention that `pep517-build` isn't really a thing anymore regardless
> Couple of docs tweaks

- src/build/__init__.py
- tests/test_projectbuilder.py
> build: fix calling hooks with relative output directory

- src/build/env.py
- tests/test_env.py
> env: pop PIP_REQUIRE_VIRTUALENV from isolated environment

- src/build/__init__.py
Looks like this accidentally says `pyproject.yml`.
This is purely cosmetic, of course.
One free t-shirt please?
> Fix error message in ProjectBuilder

- src/build/__init__.py
- tests/packages/test-bad-backend/pyproject.toml
- tests/test_integration.py
- tests/test_projectbuilder.py
This has been moved out of the ProjectBuilder constructor, since the ProjectBuilder is constructed before the isolated build environment is constructed and not executed IN the isolated environment, this check is not relevant.
Fixes GH-98.
> Remove check for the existence of build-backend

- docs/source/index.rst
- setup.cfg
- tests/test_integration.py
> setup.cfg: rename entrpoint script to pyproject-build

- .pre-commit-config.yaml
- docs/source/conf.py
- pyproject.toml
- setup.cfg
- setup.py
- tests/conftest.py
- tests/packages/legacy/setup.py
- tests/test_integration.py
- tests/test_main.py
- tests/test_projectbuilder.py
Move off from mirrors-isort that's now deprecated, and migrate
configuration to pyproject.toml
> Upgrade isort

- .pre-commit-config.yaml
setup-cfg-fmt now validates our implementation classifiers
> Bump setup-cfg and isort

- .pre-commit-config.yaml
- setup.cfg
- tests/conftest.py
- tests/test_integration.py
- tox.ini
tox.ini:
- include py39
- add a tox environment for running the pre-commit check
- append description for the path, sdist, wheel variants
- use github over gitlab for all pre-commit checks
- enable coverage context collection and rendering in html
- move coverage temp files to the envtmpdir
- run integration tests by default
integration tests:
- Make it parallel safe
- Only download as much as needed instead of all
- Move acquisition of the pkgs to where the test is
- Allow running them without the --run-integration flag if only pytest target
- Wrap URL into Request to make it work behind proxy firewall too (SSL_CERT_FILE set)
- building via pyproject-build is validated via existance of the console entrypoint rather than the existance of the PYTHONPATH variable (more accurate, and IDE …
> Improve tox.ini and integration tests

- README.md
- docs/source/conf.py
- docs/source/differences.rst
- docs/source/index.rst
- docs/source/installation.rst
- src/build/__init__.py
> docs: fix project name

- .dockerignore
- .gitignore
- setup.cfg
- src/build/__main__.py
- src/build/env.py
- tests/conftest.py
- tests/test_env.py
- tox.ini
Instead of provisioning via ensurepip. This speeds up isolated build environment creation.
While implementing this I had to also address https://github.com/pypa/build/issues/120 to make the CI pass. They're separate commits though. 
> Borrow pip from host python if available

- src/build/__main__.py
For some reason mypy isn't saying anything in the CI but locally it
complains:
src/build/__main__.py:26: error: Incompatible types in assignment (expression has type "Callable[[str, Type[Warning], str, int, Optional[TextIO], Optional[str]], None]", variable has type "Callable[[Union[Warning, str], Type[Warning], str, int, Optional[TextIO], Optional[str]], None]")
> main: fix warnings.showwarnings compatibility

- setup.cfg
- src/build/__init__.py
- src/build/__main__.py
- src/build/_compat.py
- src/build/env.py
- tests/test_env.py
- tests/test_main.py
- tests/test_projectbuilder.py
- tox.ini
Create the isolated build environment upfront to avoid executable, pip executable or path not yet set. Remove unused code segments.
As promised in https://github.com/pypa/build/pull/140 this is the follow-up PR to clean up the env code a bit and avoid some redundant type casts. There have been many code segments we don't need actually anymore with the switch to venv/virtualenv. While doing it I've taken the liberty to add a few tests to get 100% coverage for the module.
> Refactor to simplify the env package

- .github/workflows/check.yml
- tox.ini
People can opt in via posargs.
> tox: don't run integration tests by default

- setup.cfg
- src/build/env.py
- tests/conftest.py
- tests/test_env.py
- tests/test_integration.py
- tox.ini
Using the pytest-xdist module to run up to number of user CPUs in
parallel. Fixed some bugs discovered by doing so.
> Run test suite in parallel

- src/build/__init__.py
As discussed in https://github.com/pypa/build/pull/157 this is not a good default for the programmatic API.
> Remove `srcdir` default value

- setup.cfg
- src/build/__init__.py
The impetus for these changes is to make `build` easier to use as a library in combination with type checking.
> Annotate public API in full and add py.typed marker file

- .github/workflows/check.yml
> ci: decapitaze os name to match current style

- src/build/__main__.py
- tests/test_main.py
As discussed in #69 and #157, a predictable default is (marginally :) preferable.
> Default to `{srcdir}/dist` for `outdir` if option is omitted

- setup.cfg
- src/build/__init__.py
- Moved the upstream to PyPA
- Fixed building with isolation in a virtual environment
- Renamed the entrypoint script to pyproject-build (!)
- Removed default arguments from all paths in ProjectBuilder (!)
- Removed ProjectBuilder.hook (!)
- Renamed __main__.build to __main__.build_package (!)
- Changed the default outdir value to {srcdir}/dest (!)
- Removed env.IsolatedEnvironment (!)
- Added env.IsolatedEnv abstract class
- Added env.IsolatedEnvBuilder (replaces env.IsolatedEnvironment usages)
- Added python_executable argument to the ProjectBuilder constructor
- Added --version/-V option to the CLI
- Added support for Python 3.9
- Added py.typed marker
- Various miscelaneous fixes in the virtual environment creation
- Many general improvements in the documentation
- Documentation moved …
> release 0.1.0

- .readthedocs.yml
autodoc-typehints is not able to display type hints under
Python 3.7 and earlier without the `typed_comments` extra.
Closes #118.
> docs: build on RTD using Python 3.8 

- tests/conftest.py
- tests/packages/test-optional-hooks/pyproject.toml
- tests/test_projectbuilder.py
We're testing this against a local backend which does not expose
any hooks.
See #132.
> Verify `get_dependencies` returns empty set when its hooks are undefined

- src/build/__init__.py
- tests/test_projectbuilder.py
When the `build-backend` field was missing, we would append the default
PEP 518 `requires` to the source tree `requires`.  This is in contrast
to pip which leaves `requires` unmodified.  It was therefore possible
to create sdists which pip would not have been able to consume.
Closes #107 by way of not modifying the `requires` list.
> Align builder with pip when backend is missing

- src/build/__init__.py
With `mypy --strict` (or `pyright: strict`, etc.) you cannot
import symbols which are not explicitly (re-)exported.
This can be accomplished in one of two ways: using `__all__`
or with `import x as x` if a symbol is imported from another module.
> build: add exports to __init__.py for strict type checking support

- .pre-commit-config.yaml
When running tox in parallel, pre-commit might run at the same time as
the tests. This is problematic because the tests will remove read
permissions from the file and pre-commit won't be able to reade it. So,
we will ignore it.
> pre-commit: exclude test-no-permission/pyproject.toml from check-toml

- src/build/__main__.py
- tests/test_main.py
PEP 517 says that we should use the get_requires_for_* hooks to fetch
extra build dependencies the backend might specify. Currently, we are
not installing these dependencies into the isolted environment, this
patch addresses that.
It also slightly changes the isolation build logic to create a isolated
environment for each distribution we want to build. Since we are now
calling the get_requires_for_{sdist,wheel} hooks to install extra
dependencies, the might change between a sdist and wheel. Since we do
not want sdist dependencies leaking into the environment where the wheel
is built, or vice-versa, we need to separate the environments.
Perhaps in the future we could try to optimize this to see if the sdist
and wheel dependencies are the same and avoid creating a new isolated
environment …
> build: install backend specified dependencies when building with isolation

- README.md
- docs/cli.rst
- docs/index.rst
Document example CLI usage in the README and on the home-page of the docs. Move CLI help to a separate docs page "CLI Usage"
> Document CLI usage

- src/build/__init__.py
This fixes https://github.com/pypa/build/issues/211. It replaces incorrect PR https://github.com/pypa/build/pull/212.
> mypy: fix importlib.metadata import error

- CHANGELOG.rst
- docs/changelog.rst
- docs/index.rst
- setup.cfg
> docs: add changelog

- setup.cfg
- src/build/__init__.py
- src/build/__main__.py
- src/build/env.py
- tests/packages/inline/build.py
- tests/packages/inline/pyproject.toml
- tests/test_env.py
- tests/test_projectbuilder.py
> build: ensure console scripts are available on PATH during build

- docs/conf.py
- src/build/__init__.py
- src/build/__main__.py
- src/build/env.py
Sphinx does not extract docstrings from `__init__` - these
must be placed under the class.
> docs: improve the formatting, style and accuracy of docstrings

- CHANGELOG.rst
- src/build/env.py
- tests/test_env.py
Fixes #228
- fix: Upgrade pip for all Python < 3.7
- fix: avoid breaking so badly if pip is too old
> env: upgrade pip based on pi version (fixes Python 3.6.5-3.8 issues, including in GitHub Actions via pipx)

- src/build/__main__.py
RST treats single backticks as `:any:` role that tries
to automatically match something with that name. This
generates a warning because there's nothing to be found.
But running Sphinx in nitpicky mode turns the warning
into an error.
There's two ways of fixing this: either use double backticks
for inline code or drop them and maybe switch to double-
quotes. This change does the former.
> docs: fix sphinx syntax @ `--config-setting` doc

- CHANGELOG.rst
- src/build/env.py
- tests/test_env.py
In #231 we discovered pip is not building some dependencies in
isolation, it is using the build environment, which can become an issue
since we remove setuptools from the environment.
As suggested by @layday, this patch passes --use-pep517 to pip so that
it builds in isolation, as recomended by PEP 517.
Fixes #231
> env: pass --use-pep517 to force build isolation

- tox.ini
This ensures typing is right on Python 3 conditional branches.
Currently, we could have code that isn't compatible with Python 3 minor
version lower than Python 3.8. Running against the minimum supported
version ensures everything is checked correctly on older versions.
> tox: run mypy against the minimum supported Python 3 minor version

- CHANGELOG.rst
- src/build/env.py
- tests/test_env.py
Followup to #229. This fixes an issue I've seen trying to install `cmake` on Big Sur (Intel), and preemptively fixes an issue for Big Sur (Apple Silicon).
Edit: I'm now questioning if I got the version right for pip breaking on Big Sur Intel...
EditEdit: Ahh, I have a custom wheel cached as workaround. 🤦 Yes, 20.2 does break, as promised. 
To see the problem, `pyenv install 3.9.1`, activate it, install build, then build the following `pyproject.toml`:
```toml
[build-system]
requires = ["flit_core >=2,<4", "cmake"]
build-backend = "flit_core.buildapi"
[tool.flit.metadata]
module = "foobar"
author = "Sir Robin"
author-email = "robin@camelot.uk"
home-page = "https://github.com/sirrobin/foobar"
```
You will see `Building wheel for cmake (PEP 517)` because it's using the venv's pip 20.2.
> env: fix issue installing wheels on Big Sur

- CHANGELOG.rst
- src/build/env.py
Would have helped with https://github.com/pypa/packaging-problems/issues/450. I'm not going to have time to follow up on this, my daughter will be born in 24 or so hours. But I think the general idea is good? Hoping someone else might have a chance?
> env: old virtualenv should not be used

- src/build/__init__.py
- tests/test_env.py
- tests/test_main.py
- tests/test_projectbuilder.py
Fix #130.
I make the function signature require the user to pass in `"wheel"` explicitly. This is of course redundant, but I have a feeling we’re going to have a `prepare_metadata_for_sdist` at some point and it’s better to leave room now than having to change things later. And `prepare("wheel")` is arguably more consistent with `build("wheel")` anyway.
Due to the issues mentioned in https://github.com/pypa/build/issues/130#issuecomment-769849702, I’m *not* using the `build_wheel` fallback provided by `pep517`, and instead return `None` when the backend does not implement `prepare_metadata_for_wheel`. The returned result is stored in a member attribute and popped out when `build_wheel` is called.
> build: implement metadata preparation hook

- docs/index.rst
Right now they are in the usage section, which is wrong.
> docs: put project links in separate section

- CHANGELOG.rst
- setup.cfg
Pipx has added a feature at our request to run packages with differently named entrypoints without having to use `--spec`. This is before:
```bash
pipx run --spec build pyproject-build
```
and this will work after this PR with Pipx 0.16.1.0+:
```bash
pipx run build
```
See pipxproject/pipx#600.
> setup.cfg: support direct usage from pipx run in 0.16.1.0+

- CHANGELOG.rst
- src/build/__init__.py
- tests/test_projectbuilder.py
Fixes #250
This avoids a `UnicodeDecodeError` when reading `pyproject.toml` files containing unicode characters on Windows. These characters may be present in a project's metadata, such as its description or an author's name.
Furthermore, the [TOML specification](https://toml.io/en/v1.0.0#spec) requires files to be encoded in UTF-8.
> build: use UTF-8 encoding when reading pyproject.toml

- src/build/__init__.py
- tests/test_projectbuilder.py
An OS error in `_working_directory` would have been incorrectly
transformed into a `BuildBackendException`.
> build: un-nest `chdir` context manager

- docs/installation.rst
This PR adds some quick documentation about an extra optional dependency and is motivated by #253.
> docs: document "virtualenv" extra dependency

- tests/test_integration.py
We extract the github tarballs and invoke build on the extracted
contents, but inside them there is a folder with the project sources,
which is where the build should be invoked.
> tests: fix build being invoked in the wrong path for integration tests

- .github/workflows/check.yml
It's no longer necessary, it supports tokenless uploads for quite a while now.
> ci: don't pass a token to the codecov action

- CHANGELOG.rst
- src/build/env.py
- tests/test_env.py
Matching the `python -m venv` default, see https://github.com/python/cpython/blob/2e789a1f1d84b343a996e8654590703b5fbdd441/Lib/venv/__init__.py#L403-L406.
Closes #271.
> env: use symlinks except on Windows

- CHANGELOG.rst
- src/build/__init__.py
- src/build/__main__.py
- tests/test_main.py
- tests/test_projectbuilder.py
> build: rename get_dependencies to get_requires

- CHANGELOG.rst
- setup.cfg
- src/build/__main__.py
It seems Windows has settings to enable/disable color support by default
and we'd have to use low level Windows APIs to force enable, so I am
just gonna remove colors altogether. Shouldn't really be a big deal as
they are only used for the ERROR and WARNING prefixes.
> main: disable colors on windows

- .github/workflows/test.yml
- setup.cfg
Tests that use ensurepip are a bit flaky, let's rerun tests to avoid us
having to manually rerun the whole CI pipeline.
> ci: rerun tests if they fail with subprocess.CalledProcessError

- CHANGELOG.rst
- src/build/__main__.py
- tests/conftest.py
- tests/packages/test-cant-build-via-sdist/backend_bad_sdist.py
- tests/packages/test-cant-build-via-sdist/pyproject.toml
- tests/packages/test-setuptools/setup.cfg
- tests/test_integration.py
- tests/test_main.py
> main: build binary distributions via sdists by default

- CHANGELOG.rst
- src/build/__main__.py
> main: remove import side-effects

- setup.cfg
We have now dropped Python 2, this should be disabled, otherwise
setuptools will still build a py2.py3 wheel.
> setup.cfg: disable universal wheel

- CHANGELOG.rst
- src/build/__main__.py
- tests/test_main.py
> main: fix replacing color codes in tracebacks

- CHANGELOG.rst
- docs/installation.rst
- setup.cfg
- src/build/__init__.py
- tests/constraints.txt
- tests/test_projectbuilder.py
> build: switch to tomli for TOML v1 compliant parser

- src/build/__main__.py
- tests/test_main.py
7ed0a6bf06e05e6ccc72a99fe8194ebb9a2f1d20 added the new line in the
_error call, but we want it before.
> main: fix missing dependencies error

- tests/test_integration.py
I guess it now dropped support for legacy versions.
> tests: integration: use PEP 440 version as setuptools-scm fallback

- CHANGELOG.rst
- setup.cfg
- src/build/__init__.py
- src/build/env.py
- src/build/util.py
- tests/conftest.py
- tests/packages/test-metadata/backend.py
- tests/packages/test-metadata/pyproject.toml
- tests/test_util.py
> util: add project_wheel_metadata

- CHANGELOG.rst
- src/build/__init__.py
- tests/test_projectbuilder.py
> build: validate `build-system` table schema

- setup.cfg
> Fix coverage data collection

- src/build/env.py
- tests/test_env.py
After https://github.com/python/cpython/commit/6811fdaec825bd6ab64e358a4b480108f5634d2d
the venv module produces spurious warnings for venv paths which contain
DOS-encoded parts e.g. "USER\~1" in "C:\Users\USER~1".
`tempfile.gettempdir()` returns legacy paths like these for
user temp dirs.
MRE:
python -c "import tempfile
import venv
venv.create(tempfile.mkdtemp())"
Actual environment location may have moved due to redirects, links or junctions.
Requested location: "C:\Users\RUNNER~1\AppData\Local\Temp\tmpfoobar\Scripts\python.exe"
Actual location:    "C:\Users\runneradmin\AppData\Local\Temp\tmpfoobar\Scripts\python.exe"
Closes #413.
> env: prevent warning from being emitted on venv creation

- pyproject.toml
- tests/conftest.py
- tests/test_env.py
- tests/test_main.py
- tests/test_util.py
- tox.ini
WIP at the moment. These are the 11 Windows PyPy failures:
```
FAILED tests/test_env.py::test_isolated_env_log - subprocess.CalledProcessErr...
FAILED tests/test_main.py::test_build_package - subprocess.CalledProcessError...
FAILED tests/test_main.py::test_build_package_via_sdist - subprocess.CalledPr...
FAILED tests/test_main.py::test_build_package_via_sdist_cant_build - subproce...
FAILED tests/test_main.py::test_output[via-sdist-isolation] - SystemExit: 1
FAILED tests/test_main.py::test_output[wheel-direct-isolation] - SystemExit: 1
FAILED tests/test_util.py::test_wheel_metadata[True] - subprocess.CalledProce...
FAILED tests/test_util.py::test_wheel_metadata_isolation - subprocess.CalledP...
FAILED tests/test_util.py::test_with_get_requires - subprocess.CalledProcessE...
FAILED …
```
> ci: fix broken tests

- src/build/env.py
Python distributors with custom default installation scheme can set a
scheme that can't be used to expand the paths in a venv.
This can happen if build itself is not installed in a venv.
The distributors are encouraged to set a "venv" scheme to be used for this.
See https://bugs.python.org/issue45413
and https://github.com/pypa/virtualenv/issues/2208
Since Python that ships with the macOS developer tools does not have the "venv"
scheme yet, we keep the special case below. Once it gains the "venv" scheme,
it will be preferred.
Fixes https://github.com/pypa/build/issues/433
> env._find_executable_and_scripts(): Prefer the venv installation scheme if it exists

- src/build/env.py
- tests/test_env.py
As a result of https://github.com/python/cpython/pull/31034,
venv now calls sysconfig.get_paths. This messes up the mock call
count.
The change to using Signature.bind isn't strictly necessary, but fixes
the initial symptom (since venv calls sysconfig.get_paths without
kwargs). This also means we can use sysconfig.get_paths however we want.
> Fix test_executable_missing_post_creation for Python 3.11, PyPy

- src/build/env.py
- tests/test_env.py
The issue and solution is the same as OSX.
The venv scheme wasn't standardised yet, so it's not using it yet.
Fixes: https://bugs.debian.org/1009916
> Handle Debian's posix_local scheme

- tests/conftest.py
The issues with pypy, windows, and venv were fixed for the 7.3.9 release.
> PyPy >= 7.3.9 fixed the venv problem on windows

- .github/workflows/check.yml
- .github/workflows/test.yml
- .pre-commit-config.yaml
- .readthedocs.yml
- CHANGELOG.rst
- setup.cfg
- src/build/__init__.py
- src/build/__main__.py
- tests/test_env.py
- tests/test_module.py
- tox.ini
A few fixes and cleanups.
- docs: update changelog
- chore: minor cleanups from #361
- chore: minor style check additions
- ci: update actions
> chore: update changelog, minor touchups

- CHANGELOG.rst
The changelog used am ambiguous date format (e.g. `dd-mm-yyyy`) which is understood only in a very [few countries](https://en.wikipedia.org/wiki/Date_format_by_country#Listing) in the world. The vast majority of software projects have standardized on the non-ambigious [ISO format](https://en.wikipedia.org/wiki/ISO_8601) (e.g. `yyyy-mm-dd`) which is not only used in changelogs but also for most other situations where dates or date times are needed. Please consider accepting this change as it will make reading the change log less confusing.
https://keepachangelog.com/en/1.0.0/
> Changed ambigous date format to ISO

- tox.ini
The output from MyPy is currently missing color.
> types: include color in tox output

- docs/api.rst
- src/build/__init__.py
- src/build/__main__.py
- src/build/env.py
- src/build/util.py
Pulling a few more changes out of #361 to make rebasing / merging easier.
- build: add `BuildSystemTableValidationError` to module exports
- multi: use same `__all__` style and placement in all modules
- main: remove redundant re-export
- multi: use module names for loggers
- docs: remove API doc blurb
- build: make srcdir read-only
- ~~docs: normalize formatting~~
> chore: more small changes from #361

- src/build/env.py
- tests/test_env.py
Similar to #395, this helps with bootstrap issues with python < 3.8.
> Only import importlib_metadata when needed

- src/build/__init__.py
- tests/test_main.py
- tests/test_projectbuilder.py
I would also change parameter `distribution` to `dist_type`, because it is not the actual package that is being meant here. Tell me if it is ok to do, and I'll add commits here.
> build: clarify that dependencies are build dependencies

- .gitignore
After checking out this project, I found that files in src/build weren't being tracked and that src appeared empty in my editor. Turns out, I used a common pattern of ignoring `build` in my global gitignore (which I manage centrally rather than copying and mutating boilerplate across hundreds of projects).
This change ensures that if the user has ignored `build`, the `src/build` folder won't be ignored in this project.
> git: unignore src/build in case user ignores build

- tests/test_main.py
In [nixpkgs](https://github.com/NixOS/nixpkgs), we run the tests in parallel using `pytest-xdist`, and I can consistently see a failure on my M1 Mac machine in `test_main.py#test_venv_fail` related to the actual stdout containing color escape sequences when none were expected.
If I reload `build.__main__` as is done in other tests, the failure goes away for me.
> tests: better isolate test_venv_fail

- .github/workflows/test.yml
- src/build/__main__.py
- tox.ini
> main: disable `colorama` on Linux and flush output

- .github/workflows/test.yml
- CHANGELOG.rst
- pyproject.toml
- src/build/env.py
- tests/test_env.py
- tests/test_projectbuilder.py
> ci: move to final release of 3.11

- src/build/__init__.py
- tests/test_projectbuilder.py
As per https://github.com/pypa/build/pull/535#issuecomment-1321163124 changing the working directory seems to be redundant. So let's remove it. (This also makes build thread-safe.)
Closes #535
> build: remove redundant change of working directory

- .github/workflows/test.yml
This patch is intended to lower the maintenance burden of having to manually go through each matrix subjob name in the branch protection repository settings. It allows to only include the `check` job in the branch protection and it will robustly determine if the dependencies have succeeded or not.
It is currently mostly serves the Python ecosystem in projects like aiohttp, attrs, cryptography, pydantic, open edX, pip etc. But I've also seen other communities picking it up lately, like the AWS Rust SDK and even the engine powering https://dev.to, to my surprise. Strictly speaking, it is agnostic.
Ref: https://github.com/marketplace/actions/alls-green#why
> Introduce a centralized GHA check/gate job

- tests/test_projectbuilder.py
> tests: fix for PEP 685 in packaging 22

- .pre-commit-config.yaml
- pyproject.toml
- tests/packages/test-bad-wheel/backend_bad_wheel.py
- tests/packages/test-no-prepare/backend_no_prepare.py
- tests/test_integration.py
- tests/test_util.py
- tox.ini
As a first step, this ports all of our existing flake8 rules to Ruff. I have omitted pyupgrade for which Ruff has partial support.
> infra: replace flake8 with ruff

- CHANGELOG.rst
- src/build/__init__.py
- src/build/__main__.py
- src/build/_exceptions.py
- src/build/_util.py
- src/build/env.py
- src/build/util.py
- tests/test_env.py
- tests/test_main.py
- tests/test_projectbuilder.py
- tests/test_self_packaging.py
This is a more modest set of changes than I had in #361.  Changing the runner's signature to make removing variables from the environ possible can come in a follow-up PR.  Just as #361, this removes the env builder, redefines the isolated env interface, and adds an isolated env constructor to the project builder.
> Refactor `IsolatedEnv`, take two

- CHANGELOG.rst
- src/build/util.py
> util: allow passing alternative runner to `project_wheel_metadata`

- src/build/env.py
- tests/test_env.py
- tests/test_projectbuilder.py
- tox.ini
Fixes failures when PYTHONWARNDEFAULTENCODING=1. Fixes #577.
> Specify encoding.

- .pre-commit-config.yaml
- pyproject.toml
Ruff now supports lines between types.
> infra: use latest Ruff instead of isort

- pyproject.toml
- tests/conftest.py
In https://github.com/pypa/build/issues/587, the exact version of pip would help debug why our CI isn't seeing this issue (at least I think it would). Let's report the versions of things we care about in our test header to make such debugging easier.
> tests: report installed versions of common packages

- docs/index.rst
> docs: remove direct references to PEP 517 in docs landing page

- pyproject.toml
See https://github.com/charliermarsh/ruff/pull/3569.
> config: support running Ruff 0.258+ directly on source

- docs/release.rst
https://pypa-build.readthedocs.io/en/latest/release.html
> Fix link to installation page in docs

- pyproject.toml
- src/build/_util.py
- src/build/env.py
- tox.ini
This fixes the issue with two type ignores no longer being needed, updates mypy, moves the configuration out of extras (it was outdated and not helpful to force pin mypy in extras, and not required to use mypy to type anyway, and removes the requirement that build be installed to type check (which is not needed).
> fix: mypy update

- pyproject.toml
- tests/conftest.py
This was missing, caught by scikit-hep's [repo-review tool](https://scikit-hep.org/developer/reporeview?repo=pypa%2Fbuild&branch=main).
> chore: isort Ruff code was missing

- .github/workflows/reusable-change-detection.yml
- .github/workflows/reusable-docs.yml
- .github/workflows/reusable-pytest.yml
- .github/workflows/reusable-type.yml
- .github/workflows/test.yml
- README.md
This change slightly refactors parts of the GitHub Actions CI/CD workflow definitions to make it possible to rely on the single check gate in branch protection and declutter the main workflow definition.
It reproduces the original efforts of skipping the unnecessary checks depending on the files changed via dynamically determined variables.
> 🎨🧪 Modularize GHA workflow through reuse

- pyproject.toml
These are no longer needed (since about March). See https://github.com/scientific-python/cookie/issues/201 for details.
> chore: remove unneeded target-version

- .pre-commit-config.yaml
See https://github.com/scientific-python/cookie/pull/200.
> pre-commit: ruff moved to astral-sh

- pyproject.toml
- src/build/__main__.py
- src/build/_util.py
See https://peps.python.org/pep-0706/.
> main: filter out malicious files when extracting tar archives

- src/build/env.py
Fix #510. If a user is using `-n`, skip the cost of importing virtualenv.
> main: avoid cost of importing virtualenv if not using it

- src/build/__main__.py
- tests/test_main.py
Fixes builds for packages like psycopg2(for example if the `--pg-config` config setting needs to be set) that can hard error in some cases without `config_settings` being passed to their `get_requires_for_build` hooks.
> main: ensure config_settings are passed to get_requires_for_build

- pyproject.toml
- tests/test_main.py
- tests/test_self_packaging.py
- tests/test_util.py
Fixes #648. Adds a network marker for tests using the network.
Tested by disabling wifi and running `pytest -m "not network"`.
> tests: add network marker

- pyproject.toml
@pradyunsg's furo is broken with Sphinx 6. I don't like requiring a week-old version of something (furo), but that's the only releases compatible with Sphinx 7. I think I like requiring a very recent Furo better than capping Furo, but I'm open to suggestions, just trying to restore our CI, which has been broken for days.
> docs: bump furo/sphinx

- pyproject.toml
Building with build isn't the same as building with flit, due to flit-core not behaving the same when using standardized tools. :(
This adds all the files in the git repo, just like building with flit would. I've used check-sdist to do so, but haven't added it as a pre-commit check (yet).
Closes #656.
> fix: include all files in SDist

- docs/changelog.rst
- pyproject.toml
- tests/test_self_packaging.py
Followup to #657, tests didn't run due to no changes in src dir.
> fix: tests & file inclusion update

- pyproject.toml
- src/build/__init__.py
- src/build/__main__.py
- src/build/env.py
- tests/conftest.py
- tests/packages/test-cant-build-via-sdist/backend_bad_sdist.py
- tests/test_main.py
- tests/test_main_helpers.py
- tests/test_projectbuilder.py
Some cleanup based on Ruff checks.
> chore: add some exception handling minor cleanup checks

- .github/workflows/reusable-change-detection.yml
- CHANGELOG.rst
- pyproject.toml
> docs: update changelog for 0.11.0

- .github/workflows/cd.yml
- pyproject.toml
The artifacts can be downloaded and released from the CI build.
> ci: build and test SDist/wheels

- .pre-commit-config.yaml
- tox.ini
Suggested in https://github.com/pypa/build/pull/676#discussion_r1317680683.
> tox: format file

- pyproject.toml
This PR fixes `ruff check .` which started failing with after moving the `exclude` to `[ruff.lint]`
```
ruff failed
Cause: TOML parse error at line 2, column 19
|
2 | requires = ['bad' 'syntax']
|                   ^
invalid array
expected `]`
```
`ruff.exclude` and `ruff.lint.exclude` have slightly different semantics: 
* `ruff.exclude`: Excludes files from your project, so that ruff skips them for all commands. This also prevents ruff from loading configuration files in excluded directories. 
* `ruff.lint.exclude`: Excludes files from linting only. However, ruff loads the files (and related configurations).
You want `ruff.lint.exclude` to avoid the intentionally malformed configuration. 
Question: Could we improve our documentation to make this distinction more clear?
`ruff check .` no …
> Fix Ruff `test-bad-syntax` exclusion

- pyproject.toml
- src/build/_importlib.py
- tests/test_util.py
Closes https://github.com/pypa/build/issues/692.
> Use importlib_metadata for Python < 3.10.2

- .pre-commit-config.yaml
- pyproject.toml
- src/build/__main__.py
- src/build/_exceptions.py
- tests/packages/test-metadata/backend.py
- tests/test_main.py
- tests/test_projectbuilder.py
This is 30x faster than black, drops a dependency, and supports single quotes as a setting.
See https://astral.sh/blog/the-ruff-formatter & https://github.com/scientific-python/cookie/pull/299.
> fix: switch to ruff-format

- pyproject.toml
This is now recommended (since February), based on the PythonBytes mention today.
> chore: use exclude_also for coverage

- CHANGELOG.rst
- src/build/__init__.py
- tests/packages/test-invalid-requirements/pyproject.toml
- tests/packages/test-no-prepare/pyproject.toml
- tests/packages/test-setuptools/pyproject.toml
- tests/packages/test-typo/pyproject.toml
- tests/test_main.py
- tests/test_projectbuilder.py
PEP 517 doesn't mandate depending on `wheel` when a `__legacy__` setuptools fallback is used. Historically, it used to be assumed as necessary, but later it turned out to be wrong. The reason is that `setuptools`' `get_requires_for_build_wheel()` hook already injects this dependency when building wheels is requested [[1]]. It also used to have this hint in the docs, but it was corrected earlier [[2]].
This patch removes `wheel` from said `requires` list fallback.
[1]: https://github.com/pypa/setuptools/blob/v40.8.0/setuptools/build_meta.py#L130
[2]: https://github.com/pypa/setuptools/pull/3056
> Stop injecting `wheel` as a build dep fallback

- .github/workflows/test.yml
Our CI has been broken for over four months, and it wasn't obvious even though we were running scheduled jobs _daily_. This changes it to weekly. Might be worth pointing out that anyone making a PR with failing CI should check the last scheduled run before worrying about it.
> ci: reduce frequency

- pyproject.toml
- tox.ini
This seems to be the replacement for the unmaintained bump2version, which is a fork of the unmaintained bumpversion...
> chore: add an easy way to bump the version

- src/build/env.py
Tiny bit of cleanup that might help work on #733.
> refactor: pull out pip checks

- src/build/env.py
- tests/conftest.py
- tests/test_env.py
- tests/test_main.py
Trying #733 out. Pip is used if it is in the same environment as build and new enough. Saves a bit of time setting up the venvs. Haven't worked on tests yet.
From quick testing building both an sdist and wheel for itself with virtualenv installed this goes from about 4.7 seconds to 3.2 seconds. With `venv` only, it goes from 10.5 seconds to 4.4 seconds.
FYI, with `uv` (hacked in) it took 2.36 secs.
(This is a very simple build, of course, with only a small handful of deps)
uv's experimental native build support took 571ms, but that's only building the wheel (above is SDist and wheel).
> feat: use external pip if available

- src/build/env.py
- tests/test_env.py
Compiling bytecode is supposed to make usage more consistent for interaction. But it compiles everything, which isn't required for a single use non-interactive temporary environment. We can potentially save a bit of time this way.
This will need to be skipped for the uv backend in #751, since uv defaults to not compiling bytecode, and instead requires a flag to do so (most recent version). But flags aren't identical anyway.
> perf: avoid compiling unused bytecode

- CHANGELOG.rst
- src/build/__main__.py
> fix: support min width not detectable

- src/build/_builder.py
- src/build/_types.py
> build: add `editable` to dist type

- .github/workflows/cd.yml
- docs/installation.rst
- docs/release.rst
This adds Trusted Publisher based PyPI publishing and GitHub Artifact Attestations for the binaries, which can be queried from GitHub after publishing at https://github.com/pypa/build/attestations. Not supported on PyPI yet, [PEP 740](https://peps.python.org/pep-0740/) will add support.
Replaces https://github.com/pypa/build/pull/759. Needs setup on PyPI (which I can do if we think this is a good idea).
WDYT?
- https://github.blog/2024-05-02-introducing-artifact-attestations-now-in-public-beta/
- https://docs.github.com/en/actions/security-guides/using-artifact-attestations-to-establish-provenance-for-builds
- PEP 740
> ci: publish artifact attestation and PyPI packages

- tests/test_integration.py
- tests/test_main.py
The tests test_build and test_verbose_output both fail when run without a network connection, so mark them appropriately.
> tests: mark more network tests

- docs/conf.py
- docs/index.rst
- src/build/_types.py
Figured some folks might find them useful.
> docs: Add a few intersphinx links to the Python Packaging User Guide

- tests/test_env.py
- tests/test_integration.py
Skip the tests that need uv when uv is not installed.  This makes it easier for Linux distros that package build to avoid a build-time dependency on uv.
> tests: optional uv

- .github/release.yml
The autogenerated summary is handy for preparing the release notes, but it includes a lot of bot PRs. This filters them.
> ci: remove bot comments from generated release notes

- README.md
The readme doesn't introduce very much about the package. This puts a few more commonly needed things in. I can make some of the references links, but thought I'd start with this for discussion / feedback.
> docs: more info in README

- tests/packages/test-no-prepare/backend_no_prepare.py
- tests/packages/test-no-prepare/pyproject.toml
- tests/packages/test-no-prepare/setup.cfg
- tests/test_projectbuilder.py
By replacing setuptools with a bare-bones wheel builder.
Close #823.
> tests: fix  under pyproject-hooks 1.2

- src/build/__init__.py
Just metadata updates, to get the 3.13 classifier on PyPI.
> chore: 1.2.2.post1

- .github/workflows/cd.yml
This is now the default. (And they are now accepted on PyPI! Looks like post1 has the attestation https://pypi.org/project/build/#build-1.2.2.post1.tar.gz).
> ci: explicit attestations no longer required

- docs/installation.rst
On conda-forge, this package is called "python-build", not "build". However, this information is only given in README.md and not in docs/installation.rst.  Users are likely to read the documentation on https://build.pypa.io/ only, and they are likely to think that the name of the package on conda-forge is also "build", which will make them get into trouble.  Fix this problem here.
> docs: Add method of installation via conda

- tests/packages/test-cant-build-via-sdist/backend_bad_sdist.py
- tests/packages/test-setuptools/setup.cfg
- tests/test_main.py
This is throwing a warning, so let's remove it.
> tests: remove universal setting for setuptools

- src/build/env.py
In the debundled pip version distributed on Gentoo systems, `pip install --python` is nonfunctional since it expects all of pip's dependencies to be present in the (empty) virtual environment.  Detect this case by the removal of `pip._vendor` package, and use the "no valid outer pip" codepath.
Bug: https://bugs.gentoo.org/934922
> fix: disable use of `pip install --python` for debundled pip

- tests/conftest.py
I think this will fix our flaky tests. Setuptools makes some files in-tree.
> tests: better support for parallel testing

- pyproject.toml
- tox.ini
This is about 40% faster on Python 3.12+ when collecting coverage[^1] (which we are always doing). It also gets rid of a multithreading warning about build already being imported but not measured.
[^1]: When running locally without the isolation testing, which dominates the CI time, in CI it only is a few seconds faster but still something.
> tests: faster on 3.12+ and reduce warnings

- .github/workflows/reusable-pytest.yml
> ci: bump version used to run tox

- .github/workflows/reusable-pytest.yml
- tests/test_env.py
Speeds up CI a little bit. Closes #858.
> ci: try using tox-uv

- pyproject.toml
- src/build/_ctx.py
I think this is no longer needed.
> chore: drop type ignore for spec parent

- pyproject.toml
- src/build/env.py
- src/build/util.py
- tests/constraints.txt
Adapting to the new `--no-wheel` deprecation. See https://github.com/pypa/virtualenv/pull/2868.
> fix: virtualenv no-wheel

- .readthedocs.yml
- pyproject.toml
- tox.ini
Use dependency-groups, drop the `[test]`/`[docs]`/`[typing]` extras.
> chore: use dependency-groups

- src/build/env.py
Fix the exception raised if `pip` is not installed at all:
```
[...]
File "/usr/lib/python3.14/site-packages/build/env.py", line 168, in _has_valid_outer_pip
if importlib.util.find_spec('pip._vendor') is None:
~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
File "<frozen importlib.util>", line 90, in find_spec
ModuleNotFoundError: No module named 'pip'
```
This is a regression from #861 where I did not predict that `find_spec()` will actually raise when the parent package is not available. To fix it, just reorder the conditions to make sure that `pip` is installed first.
> fix: Fix `ModuleNotFoundError` when `pip` is not installed
