pypa/build

.github/workflows/checks.yml, .github/workflows/tests.yml, pyproject.toml, setup.py, tests/__init__.py, tests/test_projectbuilder.py
=> ci: add pytest

build/__main__.py, pyproject.toml, setup.py, tests/test_main.py
=> tests: add test for argument parsing in main

.github/workflows/tests.yml
=> ci: fix conditional jobs

build/__init__.py
=> build: add ProjectBuilder.get_dependencies()

build/__main__.py, tests/test_main.py
=> main: do not modify sys.argv

.github/workflows/tests.yml, build/__init__.py, build/__main__.py, tests/test_main.py
=> build: allow passing config_settings to the backend

codecov.yml
=> codecov: disable the bot comment

.github/workflows/tests.yml, noxfile.py
=> ci: run nox jobs

.github/workflows/tests.yml
=> ci: also run tests on windows and macos

.github/workflows/tests.yml
=>  ci: also run tests on pypy

.pre-commit-config.yaml, setup.cfg
See https://github.com/timothycrosley/isort/issues/1247
=> isort: default modules to third party

src/build/env.py, tests/test_env.py
This tests if the required environment directories are provided by
IsolatedEnvironment.
=> Better tests for `IsolatedEnvironment` and some minor fixes

src/build/env.py, tests/test_env.py
=> env: fix installing requirements with markers

src/build/env.py, tests/test_env.py
=> env: export path as read-only

setup.cfg
=> setup.cfg: make the wheel universal

src/build/__init__.py, tests/test_projectbuilder.py
=> build: change directory to the project directory when running the hooks

tests/test_main.py, tests/test_projectbuilder.py
=> tests: autospec all dummy mocks

.github/workflows/tests.yml, noxfile.py, requirements-dev.txt, tests/conftest.py, tests/test_integration.py
=> nox: test invoking/installing via PYTHONPATH, sdist and wheel

src/build/__init__.py, tests/test_projectbuilder.py
=> build: raise warning when we verify extras

src/build/env.py, tests/conftest.py, tests/test_env.py
=> env: use venv on Python 3

src/build/env.py
=> env: add documentation

src/build/env.py
=> env: make MANIPULATE_PATHS private

.pre-commit-config.yaml, docs/source/conf.py, src/build/__init__.py, tests/test_env.py
=> pre-commit: add double-quote-string-fixer

.pre-commit-config.yaml, noxfile.py, pyproject.toml, setup.cfg, src/build/__init__.py, src/build/__main__.py, src/build/env.py, tests/conftest.py, tests/packages/legacy/legacy/__init__.py, tests/packages/legacy/setup.py, tests/packages/test-flit/test_flit/__init__.py, tests/test_env.py, tests/test_integration.py, tests/test_main.py, tests/test_projectbuilder.py
=> build: adopt black codestyle

setup.cfg, src/build/env.py, tests/conftest.py, tests/test_env.py, tests/test_integration.py, tests/test_main.py
=> Fix failing CI

.github/workflows/check.yml, .pre-commit-config.yaml, setup.cfg, tox.ini
=> Add support for Python 3.9

setup.cfg
=> setup.cfg: fix sphinx theme in doc requirements

README.md, docs/source/index.rst, docs/source/installation.rst, setup.cfg
=> update upstream url to PyPA

src/build/__init__.py, src/build/env.py
Address https://github.com/pypa/pep517/pull/93 until that gets a release.
=> Fix isolated environment call

tests/test_integration.py
=> Convert filter to list before checking build output

setup.cfg
=> setup.cfg: add package description

src/build/__init__.py, tests/test_projectbuilder.py
=> build: make pypa/pep517 hook private

.github/workflows/check.yml
=> ci: pass pytest arguments via PYTEST_ADDOPTS

src/build/__main__.py, tests/test_main.py
=> main: add --version/-V

src/build/__init__.py, src/build/__main__.py, tests/test_main.py, tests/test_projectbuilder.py
=> build: make `config_settings` an argument of hook calls

setup.cfg
=> setup.cfg: use mypy 0.800

.pre-commit-config.yaml
=> pre-commit: upgrade packages

CHANGELOG.rst, src/build/env.py, tests/test_env.py
=> env: upgrade pip on all versions of Python under 3.6.6

.github/CODEOWNERS
We should have done this when we invited @layday to be a maintainer 👏🏻
=> misc: add @layday to the code owners

README.md
Anyone can join via https://discord.gg/pypa
=> misc: add a shield to the Discord chat

docs/index.rst, docs/test_suite.rst
Please proofread, I have dyslexia so there may be some obvious typos I could not identify. Feel free to suggest how to improve the current draft, but don't block this PR if you want to propose any major change, we'll merge this and you can submit a followup PR.
=> docs: document the test suite

docs/test_suite.rst
=> docs: fix rendering of test suite tox example list

docs/installation.rst
=> docs: fix paragraph order

src/build/__main__.py
=> main: say that wheel and sdist targets are default if none specified

CHANGELOG.rst
=> changelog: fix typo

.github/workflows/test.yml
=> ci: test against Python 3.10

README.md
=> readme: drop uneeded cli arguments 

CHANGELOG.rst, docs/installation.rst, src/build/__main__.py
=> main: rename --skip-dependencies to --skip-dependency-check

CHANGELOG.rst, src/build/__init__.py, src/build/__main__.py
On top of #297 to avoid conflicts, should go in after.
=> build: normalize type names

CHANGELOG.rst, setup.cfg, src/build/__init__.py, tests/conftest.py, tests/constraints.txt, tests/packages/test-bad-wheel/backend_bad_wheel.py, tests/packages/test-bad-wheel/pyproject.toml, tests/packages/test-bad-wheel/setup.cfg, tests/packages/test-no-prepare/backend_no_prepare.py, tests/packages/test-no-prepare/pyproject.toml, tests/packages/test-no-prepare/setup.cfg, tests/packages/test-setuptools/pyproject.toml, tests/packages/test-setuptools/setup.cfg, tests/test_projectbuilder.py
=> build: add ProjectBuilder.metadata_path

src/build/__init__.py, tests/test_projectbuilder.py
=> build: refactor ProjectBuilder._call_backend

CHANGELOG.rst, src/build/__init__.py, tests/test_projectbuilder.py
=> build: fix calls on inexistent outdir with multiple levels

CHANGELOG.rst, src/build/__main__.py
=> main: build via sdist in an isolated temporary directory

CHANGELOG.rst, src/build/__init__.py, src/build/__main__.py, src/build/env.py, tests/conftest.py, tests/packages/test-invalid-requirements/pyproject.toml, tests/packages/test-invalid-requirements/setup.cfg, tests/test_env.py, tests/test_main.py
=> Curate output

src/build/__init__.py, src/build/env.py, tests/test_env.py, tests/test_projectbuilder.py
=> build: restore compatibility with Python 3.6 and 3.7

tox.ini
=> tox: show error codes in mypy

docs/api.rst
=> docs: api: add build.util module

tests/conftest.py, tests/test_env.py, tests/test_integration.py, tests/test_util.py
=> Minor improvements for people running the tests manually

pyproject.toml, setup.cfg, tests/constraints.txt, tox.ini
=> config: migrate tool config to `pyproject.toml`

docs/installation.rst, docs/mission.rst, setup.cfg, src/build/__init__.py
=> build/setup.cfg/docs: fix typos 

CHANGELOG.rst, docs/installation.rst, src/build/util.py
This fixes some typos across a few different files.
=> Fix various typos

tox.ini
https://github.com/pytest-dev/py/issues/273 has now been released so we can remove the workaround.
=> Remove py workaround

.pre-commit-config.yaml
See https://github.com/psf/black/issues/2964 for details.
=> pre-commit: bump black

pyproject.toml, setup.cfg, src/build/__init__.py, src/build/env.py, src/build/util.py, tox.ini
Some minor cleanup, and updates to typing.
- chore: remove wheel
- chore: minor style issue with pytest config
- typing: update mypy typing, fix Iterable -> Collection
=> chore: typing updates

pyproject.toml, setup.cfg
- chore: bump mypy version
- tests: include logging info on failures
=> chore: include logging in test output

.github/workflows/test.yml, .pre-commit-config.yaml, .readthedocs.yml
This adds prettier to our pre-commit, which styles yaml files (and potentially markdown & html if we have any eventually, even including yaml code blocks in markdown).
=> style: add prettier

docs/index.rst, docs/release.rst
=> docs: add the release process

pyproject.toml, src/build/util.py
Currently CI is broken. Also mypy was really old.
Personaly, I'm a fan of putting the mypy check in pre-commit. It's fast and auto-updated.
=> types: fix mypy check

docs/installation.rst
Suggested by @layday on Discord
=> docs: reorder installation instructions

.pre-commit-config.yaml, docs/installation.rst, pyproject.toml
A few minor cleanups I noticed.
=> chore: minor cleanup

.github/workflows/reusable-pytest.yml, pyproject.toml, tests/constraints.txt, tox.ini
=> ci: add 3.12 beta testing

README.md
This badge is the only one with a non-rounded style. Making them all match.
=> readme: touch up badge

CHANGELOG.rst, pyproject.toml, src/build/__init__.py
=> Release 1.0.0

CHANGELOG.rst, pyproject.toml, src/build/__init__.py
=> chore: release 1.0.1

CHANGELOG.rst, pyproject.toml, src/build/__init__.py
Getting ready for a release tomorrow.
- **chore: update changelog**
- **chore: bump version to 1.1.0**
=> chore: prepare for 1.1.0

pyproject.toml, src/build/__init__.py
=> release 1.1.1

pyproject.toml, src/build/env.py, tests/test_env.py
https://github.com/astral-sh/uv/pull/2301
=> uv: support double verbosity flag

tests/test_env.py
See https://github.com/pypa/build/pull/807#issuecomment-2330663178.
=> tests: add module case to uv detection

CHANGELOG.rst, src/build/__init__.py
Preping the changelog. Can add more PRs as needed, draft for now.
- **docs: prepare changelog for 1.2.2**
- **chore: bump version**
=> docs: changelog for 1.2.2

.github/workflows/reusable-docs.yml, README.md
=> docs: mention conda-forge name in README

tests/test_self_packaging.py
Support for PEP 639 was added.
=> tests: support new version of flit-core

pyproject.toml, tests/conftest.py, tests/constraints.txt, tox.ini
Tests have been broken on main for a bit. See if it can be fixed.
=> tests: fix tox min job

pyproject.toml, tests/test_integration.py
Trying to fix recent CI errors.
=> tests: fixes for errors in CI

tests/test_integration.py
Fix an issue with #915 not doing anything and an older issue that wasn't noticed before.
=> tests: fix issues with ignore

pyproject.toml, tests/test_projectbuilder.py
=> tests: fix test failure when flit-core is installed
